ClusterName=cluster
AccountingStorageEnforce = associations,limits,qos
ControlMachine=mgt01
ControlAddr=172.16.0.1
BackupController=mgt02
BackupAddr=172.16.0.2
SlurmdUser=root
SlurmctldPort=6817
SlurmdPort=6818
AuthType=auth/munge
StateSaveLocation=/var/spool/slurm/ctld
SlurmdSpoolDir=/var/spool/slurm/d
SwitchType=switch/none
#Prolog=/etc/slurm/slurm.prolog
MpiDefault=none
ProctrackType=proctrack/cgroup
ReturnToService=2
PrologFlags=contain
SlurmctldTimeout=300
SlurmdTimeout=300
InactiveLimit=0
MinJobAge=300
KillWait=30
Waittime=0
PriorityDecayHalfLife = 14-0
PriorityFavorSmall = yes
PriorityFlags = ACCRUE_ALWAYS,FAIR_TREE
PriorityMaxAge = 14-0
PriorityType = priority/multifactor
PriorityWeightAge = 1000
PriorityWeightFairshare = 15000
PriorityWeightJobSize = 1000
PriorityWeightPartition = 1000
PriorityWeightQOS = 0
SchedulerType=sched/builtin
SelectType=select/cons_res
SelectTypeParameters=CR_CPU_Memory
SlurmctldDebug=3
SlurmctldLogFile=/var/log/slurmctld.log
SlurmdDebug=3
SlurmdLogFile=/var/log/slurmd.log
JobSubmitPlugins = lua
JobCompType=jobcomp/none
JobAcctGatherType=jobacct_gather/cgroup
AccountingStorageType=accounting_storage/slurmdbd
AccountingStorageHost=mgt01
AccountingStoragePass=/var/run/munge/munge.socket.2
GresTypes=gpu
TaskPlugin=task/cgroup
AccountingStorageTRES=gres/gpu
# COMPUTE NODES
NodeName=cpu01 CPUs=128 SocketsPerBoard=2 CoresPerSocket=64 ThreadsPerCore=1 RealMemory=500000 Weight=60
NodeName=cpu[02-15] CPUs=128 SocketsPerBoard=2 CoresPerSocket=64 ThreadsPerCore=1 RealMemory=500000 Weight=60
NodeName=cpu[16-17] CPUs=192 SocketsPerBoard=2 CoresPerSocket=96 ThreadsPerCore=1 RealMemory=1100000 Weight=60
NodeName=mem01 CPUs=88 SocketsPerBoard=4 CoresPerSocket=22 ThreadsPerCore=1 RealMemory=6000000 Weight=60
NodeName=gpu[02-08] CPUs=36 SocketsPerBoard=2 CoresPerSocket=18 ThreadsPerCore=1 RealMemory=500000 Gres=gpu:8 Weight=60
NodeName=gpu01 CPUs=36 SocketsPerBoard=2 CoresPerSocket=18 ThreadsPerCore=1 RealMemory=500000 Gres=gpu:8 Weight=60


PartitionName=short Nodes=cpu01 MaxCPUsPerNode=128 MaxTime=12:00:00 DefMemPerCPU=2000 State=UP  AllowQos=ALL
PartitionName=small Nodes=cpu01 MaxCPUsPerNode=128 MaxTime=INFINITE DefMemPerCPU=2000 MaxMemPerCPU=4000 State=UP  AllowQos=ALL
PartitionName=cpu Nodes=cpu[02-15],cpu17 MaxCPUsPerNode=128 MaxTime=14-00:00:00 DefMemPerCPU=2000 MaxMemPerCPU=UNLIMITED State=UP Default=yes AllowQos=ALL
PartitionName=ruan_cpu Nodes=cpu[16-17] MaxCPUsPerNode=192 MaxTime=14-00:00:00 State=UP AllowQos=ALL AllowGroups=ruanlab Priority=2000
PartitionName=gpushort Nodes=gpu01 MaxCPUsPerNode=36 MaxTime=12:00:00 DefMemPerCPU=2000 MaxMemPerCPU=UNLIMITED State=UP AllowQos=ALL
PartitionName=gpu Nodes=gpu[02-08] MaxCPUsPerNode=36 MaxTime=14-00:00:00 DefMemPerCPU=2000 MaxMemPerCPU=UNLIMITED State=UP AllowQos=ALL
PartitionName=mem Nodes=mem01 MaxCPUsPerNode=88 MaxTime=21-00:00:00 DefMemPerCPU=65000 MaxMemPerCPU=UNLIMITED State=UP AllowQos=ALL

